### ISSUE TITLE
Não sabia com entrar em contato

### ISSUE THREAD

**Issue by g4nor4** [lemostrash/Lemostrash#1]
Oi!! acabei vendo seu usuario em um repositorio e adorei seu READ.ME, se estiver ok eu adoraria saber em como voce fez, me desculpas por entrar por contato por aqui kkkk nao sabia como

**Comment by lemostrash** [comment]
Opa, ta tranquilo hehe. Eu fiz ele misturando muitas referencias de perfis aq no github, no momento eu ainda to tentando deixar ele bem arrumado pq to achando q falta algo. A cobrinha eu peguei com um amigo, o score de código e etc é daqui 

https://github.com/anuraghazra/github-readme-stats

O foda que a galera meio que segue a mesma receita de bolo ai quase sempre vejo uns perfis quase iguais só muda a cor de alguns pontos kekakak, ai eu recomendo na minha opinião dar uma fugida do mesmo kakakak

- Se quiser um video tem esse da Raffa

https://www.youtube.com/watch?v=TsaLQAetPLU

PS.: passei uma 1h trocando a cor do jogo da cobrinha pra no outro dia ele resetar :/

**Comment by lemostrash** [comment]
Se quiser colar discord pra trocar ideia ou experiência só chamar Lemostrash#1066

**Comment by g4nor4** [comment]
Opa, não acredito só acabei vendo sua mensagem um ano depois pq o e-mail me notificou, quando fui ver se me respondeu no mesmo dia ainda k

 Muito obrigada pelos links ❤️e por responder dskodsokds  eu fiz um read.me mas fico meio feio vou dar uma olhada hehe valeu 

E eu entendo sua dor nesse meu read.me eu tentei alinhar o png por muito tempo só decepção
